### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by kittylyst**
Sources and sinks link was dead...

### CODE REVIEW

**Comment by viliam-durina** [comment]
The link works for us: http://docs.hazelcast.org/docs/jet/0.5/manual/Work_with_Jet/Build_Your_Computation_Pipeline.html#page_Choose+Your+Data+Sources+and+Sinks

The numbers in links are optional and we never use them.

**Comment by cangencer** [comment]
How are you generating/using the manual? It shouldn't need the explicit prefix to generate correct links.

**Comment by kittylyst** [comment]
I haven't generated it at all - it's a dead link on Github.

**Comment by mtopolnik** [comment]
All links are dead on GitHub, this is expected. GitHub doesn't process them the way Daux does. Closing this.

**Pull request closed without merging**
